[package]
name = "amethyst_openvr"
version = "0.1.0"
authors = ["Ellie <hi@ellie.moe>"]

[dependencies]
amethyst = { path = "../amethyst", version = "0.7.0" }
openvr = "0.5"
openvr_sys = "2.0.1"
log = "0.4"
